### PR TITLE
Update build + design language (Material 3)

### PR DESCRIPTION
**Pull request by cyb3rko**
### Changes
No behavioral changes

### Implementation details
- updated build files to current standards
- targetSDK 28 -> 34
- Gradle 4.6 -> 8.5
- AGP 3.2.1 -> 8.2.0
- Material library 1.0.0 -> 1.11.0 (including refactor to M3)

I've adopted your previous app colors, if you want to change something, feel free to do so :)

### Additional context
Authentication with credentials didn't work for me, maybe because of the very old and not updated GitHub api library.  
Maybe time to switch to another one

### CODE REVIEW

**Comment by heinrichreimer** [comment]
Thank you! Very cool! Could you please send some screenshots of the updated colors?

**Comment by cyb3rko** [comment]
Sorry, that should say "adopted", not "adapted".  
Here are some screenshots:









Does that fit?

**Comment by heinrichreimer** [comment]
Nice, that looks very good!

**Comment by cyb3rko** [comment]
Oh, you've already released a new version, that was quick :D  
I will take a closer look into the library again if there are other components which need an update as well (besides the already mentioned GitHub api).

Let's make sure especially the build config is modern enough for 2024 :)

**Comment by cyb3rko** [comment]
And especially because of the jump from Gradle 4 to Gradle 8 and AGP from 3 to 8.

**Comment by heinrichreimer** [comment]
Yeah, that would be totally awesome if you could contribute some more improvements!
I believe that, e.g., #135 would also be easy to implement.
Unfortunately, I don't have much time to maintain my Android projects anymore.

**Comment by cyb3rko** [comment]
Sure, could do that.  
There are a few things we could do here:
- Replace GitHub api (tested basic auth login with https://github.com/hub4j/github-api, works well)
- Use ViewBindings instead of findViewById calls
- Replace AsyncTask or directly
- Migrate to Kotlin?

**Comment by heinrichreimer** [comment]
All these are great suggestions!
I believe it is best to discuss these in separate issues (for example, see #153, that I just created).
You can just create issues for the remaining suggestions. If you like, you can start right away with the implementation 👍

**Comment by simonpoole** [comment]
> * Migrate to Kotlin?

We are unlikely to use dependencies that force us to include the Kotlin runtime (and the associated problems). 

Further relevant point for us are older Android devices, we currently support back to 4.1 (we will be dropping pre-5.0 support some time this year, but not yet).

**Comment by heinrichreimer** [comment]
> We are unlikely to use dependencies that force us to include the Kotlin runtime (and the associated problems).
Good point! Could you elaborate what specific issues arise with the Kotlin runtime? IIRC, the runtime and anything else should just be plain Java bytecode, no?

**Comment by simonpoole** [comment]
Main issue is pulling it in in the 1st place just for a rather, all things considered, small dependency, aka general bloat considerations.

**Comment by heinrichreimer** [comment]
Yeah, makes sense 👍

**Pull request merged**
