### PR TITLE
 Added an option to set the message minimum characters

### PR DESCRIPTION
**Pull request by rosenpin**
To reduce spam and messages like 'hi'.

Use 
`setMessageCharacterMinimum(minimum number of characters);`

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
The method should be named `setMinimumDescriptionLength()` to keep the naming consistent with the Android platform and this library.

**Comment by rosenpin** [comment]
Yeah, that's right.

**Comment by HeinrichReimer** [comment]
Ah and of course you should use [plurals](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) instead of the concatenated string.
Don't get me wrong. I really appreciate your pull request and effort. But we need to keep the code clean.

**Comment by HeinrichReimer** [comment]
There is an else case missing after `if (bodyMinChar > 0)` too :P

**Comment by rosenpin** [comment]
Wow I didn't know plurals existed.
I'll push a new commit later.

And I agree with you, no offense taken.

**Comment by HeinrichReimer** [comment]
Well the plural should look like this:

```xml
<plurals name="error_minimum_description_length">
    <item quantity="one">The description must have at least %d character.</item>
    <item quantity="other">The description must have at least %d characters.</item>
</plurals>
```
It would be perfectly fine to put this inside `strings.xml` but you could also keep it in `plurals.xml` if that's not convenient for you.

You'd access the string like this:

```java
getResources().getQuantityString(R.plurals.error_minimum_description_length, bodyMinChar, bodyMinChar);
```

That way we combine the two string resources, eliminate the need for string concatenation and keep our resources context aware and translatable.

**Comment by HeinrichReimer** [comment]
I also think throwing an exception if `bodyMinChar` is smaller or equal to zero is not a good idea.
`bodyMinChar` is 0 by default and if it is anything smaller than one we should basically just disable the length check.
In code this would be done by calling `removeError()` instead of throwing an exception.

**Comment by HeinrichReimer** [comment]
Again, thanks for your efforts and I hope you could learn something new from it.

**Comment by rosenpin** [comment]
Okay, I changed it.
You do realise though that the character/characters don't actually matter right?
I mean, if the developer sets the min character to 1, but the user will not write anything (same as 0 characters), the validation will stop here
```java
if (TextUtils.isEmpty(inputDescription.getText())) {
```
And this code will not be executed anyway 
````java 
else {
 if (bodyMinChar > 0) {
    if (inputDescription.getText().toString().length() < bodyMinChar) {
        setError(inputDescription, getResources().getQuantityString(R.plurals.air_error_short_description, bodyMinChar, bodyMinChar));
````
In other words, if the minimum is 1, this message `R.plurals.air_error_short_description` will not appear.
And since the only scenario where we should use "character" is where the minimum character count is 1, this string isn't even neccessary

**Comment by HeinrichReimer** [comment]
You're right with the minimum length. I didn't notice this would be blocked by `TextUtils.isEmpty()` anyways.
We should still keep the plurals handling because there are languages where there's a difference between  a few and a lot items in grammar. Polish is such a language.

**Pull request merged**
